version: "3.8"

services:
  api:
    build:
      context: .
    container_name: agro-api
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/agroDatabase?schema=public
      - ENCRYPTION_KEY=meusegredo32byteslong1234567890
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: bash -c "npx prisma migrate deploy && npm start"

  postgres:
    image: postgres:15
    container_name: agro-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: agroDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
